import json
import os

notebook = {
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🚀 Huấn luyện MobileNetV3 (Waste Classification) trên Kaggle\n",
        "Notebook này chứa toàn bộ quy trình: Khởi tạo dữ liệu -> Build Model -> Huấn luyện 2 Phase -> **Quantization-Aware Training (QAT)** -> Đánh giá -> Trích xuất TFLite (INT8).\n",
        "\n",
        "**Lưu ý khi chạy trên Kaggle:**\n",
        "1. Bật **GPU T100 / P100** trong cài đặt Notebook (Accelerator: GPU P100).\n",
        "2. Kiểm tra lại biến `DATA_DIR` ở Cell tiếp theo để trỏ đúng vào thư mục dataset bạn đã Upload."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "!pip install -q tensorflow-model-optimization --no-deps\n",
        "\n",
        "import os\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import tensorflow as tf\n",
        "import tensorflow_model_optimization as tfmot\n",
        "from sklearn.model_selection import train_test_split\n",
        "\n",
        "print(\"TensorFlow Version:\", tf.__version__)\n",
        "print(\"GPU Available:\", tf.config.list_physical_devices('GPU'))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# --- 1. CẤU HÌNH (CONFIG) ---\n",
        "\n",
        "DATA_DIR = '/kaggle/input/smart-waste-dataset/train' # Thay đổi nếu cần!\n",
        "OUTPUT_DIR = '/kaggle/working/'\n",
        "MODEL_SAVE_PATH = os.path.join(OUTPUT_DIR, 'mobilenetv3_waste_best.keras')\n",
        "QAT_MODEL_SAVE_PATH = os.path.join(OUTPUT_DIR, 'mobilenetv3_waste_qat.h5')\n",
        "TFLITE_SAVE_PATH = os.path.join(OUTPUT_DIR, 'mobilenetv3_waste.tflite')\n",
        "\n",
        "IMG_SIZE = (224, 224)\n",
        "BATCH_SIZE = 32\n",
        "EPOCHS = 15           # Phase 1\n",
        "FINE_TUNE_EPOCHS = 20 # Phase 2\n",
        "QAT_EPOCHS = 5        # Phase 3 (Quantization-Aware Training)\n",
        "NUM_CLASSES = 5\n",
        "\n",
        "CLASS_NAMES = ['bag_other', 'metal', 'mixed', 'paper', 'plastic']\n",
        "\n",
        "TEST_SPLIT = 0.1\n",
        "VAL_SPLIT = 0.15\n",
        "RANDOM_SEED = 16"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# --- 2. DATA LOADER ---\n",
        "\n",
        "def get_data_augmentation():\n",
        "    return tf.keras.Sequential([\n",
        "        tf.keras.layers.RandomFlip(\"horizontal_and_vertical\"),\n",
        "        tf.keras.layers.RandomRotation(0.1),\n",
        "        tf.keras.layers.RandomZoom(0.1),\n",
        "        tf.keras.layers.RandomBrightness(0.1),\n",
        "        tf.keras.layers.RandomContrast(0.1),\n",
        "    ])\n",
        "\n",
        "def load_all_filepaths_and_labels():\n",
        "    filepaths = []\n",
        "    labels = []\n",
        "    \n",
        "    if not os.path.exists(DATA_DIR):\n",
        "        print(f\"[LỖI] Không tìm thấy thư mục: {DATA_DIR}\")\n",
        "        return np.array([]), np.array([])\n",
        "        \n",
        "    for class_idx, class_name in enumerate(CLASS_NAMES):\n",
        "        class_dir = os.path.join(DATA_DIR, class_name)\n",
        "        if not os.path.exists(class_dir): continue\n",
        "            \n",
        "        for img_name in os.listdir(class_dir):\n",
        "            if img_name.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.gif')):\n",
        "                filepaths.append(os.path.join(class_dir, img_name))\n",
        "                labels.append(class_idx)\n",
        "                \n",
        "    return np.array(filepaths), np.array(labels)\n",
        "\n",
        "def get_test_set(filepaths, labels):\n",
        "    X_train_val, X_test, y_train_val, y_test = train_test_split(\n",
        "        filepaths, labels, test_size=TEST_SPLIT, stratify=labels, random_state=RANDOM_SEED\n",
        "    )\n",
        "    return (X_train_val, y_train_val), (X_test, y_test)\n",
        "\n",
        "def create_dataset_from_paths(filepaths, labels, is_training=False):\n",
        "    def parse_function(filename, label):\n",
        "        image_string = tf.io.read_file(filename)\n",
        "        image = tf.image.decode_jpeg(image_string, channels=3)\n",
        "        image = tf.image.resize(image, IMG_SIZE)\n",
        "        return image, label\n",
        "\n",
        "    dataset = tf.data.Dataset.from_tensor_slices((filepaths, labels))\n",
        "    dataset = dataset.map(parse_function, num_parallel_calls=tf.data.AUTOTUNE)\n",
        "    dataset = dataset.cache()\n",
        "    \n",
        "    if is_training:\n",
        "        dataset = dataset.shuffle(buffer_size=1000, seed=RANDOM_SEED)\n",
        "        \n",
        "    dataset = dataset.batch(BATCH_SIZE)\n",
        "    \n",
        "    if is_training:\n",
        "        data_augmentation = get_data_augmentation()\n",
        "        dataset = dataset.map(lambda x, y: (data_augmentation(x, training=True), y), num_parallel_calls=tf.data.AUTOTUNE)\n",
        "        \n",
        "    dataset = dataset.prefetch(buffer_size=tf.data.AUTOTUNE)\n",
        "    return dataset\n",
        "\n",
        "def get_train_val_splits(X_train_val, y_train_val):\n",
        "    X_train, X_val, y_train, y_val = train_test_split(\n",
        "        X_train_val, y_train_val, test_size=VAL_SPLIT, stratify=y_train_val, random_state=RANDOM_SEED\n",
        "    )\n",
        "    return (X_train, y_train), (X_val, y_val)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# --- 3. MODEL ARCHITECTURE ---\n",
        "\n",
        "def build_mobilenetv3_model(learning_rate=0.001):\n",
        "    inputs = tf.keras.Input(shape=IMG_SIZE + (3,))\n",
        "    x = tf.keras.layers.Rescaling(1./127.5, offset=-1)(inputs)\n",
        "    \n",
        "    base_model = tf.keras.applications.MobileNetV3Large(\n",
        "        input_tensor=x,\n",
        "        include_preprocessing=False,\n",
        "        include_top=False,\n",
        "        weights='imagenet'\n",
        "    )\n",
        "    \n",
        "    for layer in base_model.layers:\n",
        "        layer.trainable = False\n",
        "        \n",
        "    x = base_model.output\n",
        "    x = tf.keras.layers.GlobalAveragePooling2D()(x)\n",
        "    x = tf.keras.layers.Dropout(0.2)(x)\n",
        "    outputs = tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')(x)\n",
        "    \n",
        "    model = tf.keras.Model(inputs=inputs, outputs=outputs)\n",
        "    \n",
        "    model.compile(\n",
        "        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),\n",
        "        loss=tf.keras.losses.SparseCategoricalCrossentropy(),\n",
        "        metrics=['accuracy']\n",
        "    )\n",
        "    return model, base_model\n",
        "\n",
        "def unfreeze_and_recompile(model, base_model, learning_rate=1e-5):\n",
        "    for layer in base_model.layers:\n",
        "        layer.trainable = True\n",
        "        \n",
        "    fine_tune_at = len(base_model.layers) - 30\n",
        "    for layer in base_model.layers[:fine_tune_at]:\n",
        "        layer.trainable = False\n",
        "        \n",
        "    model.compile(\n",
        "        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),\n",
        "        loss=tf.keras.losses.SparseCategoricalCrossentropy(),\n",
        "        metrics=['accuracy']\n",
        "    )\n",
        "    return model"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# --- 4. MAIN TRAINING & QAT & EVALUATION ---\n",
        "\n",
        "print(\"1. Đang nạp danh sách dữ liệu...\")\n",
        "filepaths, labels = load_all_filepaths_and_labels()\n",
        "\n",
        "if len(filepaths) > 0:\n",
        "    print(\"2. Tách Test Set...\")\n",
        "    (X_train_val, y_train_val), (X_test, y_test) = get_test_set(filepaths, labels)\n",
        "    \n",
        "    print(\"3. Tách Train Set và Validation Set...\")\n",
        "    (X_train, y_train), (X_val, y_val) = get_train_val_splits(X_train_val, y_train_val)\n",
        "    \n",
        "    np.save(os.path.join(OUTPUT_DIR, 'test_filepaths.npy'), X_test)\n",
        "    np.save(os.path.join(OUTPUT_DIR, 'test_labels.npy'), y_test)\n",
        "\n",
        "    train_ds = create_dataset_from_paths(X_train, y_train, is_training=True)\n",
        "    val_ds = create_dataset_from_paths(X_val, y_val, is_training=False)\n",
        "    \n",
        "    model, base_model = build_mobilenetv3_model()\n",
        "    \n",
        "    callbacks_p12 = [\n",
        "        tf.keras.callbacks.ModelCheckpoint(filepath=MODEL_SAVE_PATH, save_best_only=True, monitor='val_accuracy'),\n",
        "        tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)\n",
        "    ]\n",
        "    \n",
        "    print(\"\\n--- Phase 1: Feature Extraction ---\")\n",
        "    model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS, callbacks=callbacks_p12)\n",
        "    \n",
        "    print(\"\\n--- Phase 2: Fine-Tuning ---\")\n",
        "    model = unfreeze_and_recompile(model, base_model)\n",
        "    model.fit(train_ds, validation_data=val_ds, epochs=FINE_TUNE_EPOCHS, callbacks=callbacks_p12)\n",
        "    \n",
        "    print(\"\\n--- Phase 3: Quantization-Aware Training (QAT) ---\")\n",
        "    # Tải lại trọng số tốt nhất từ Phase 2\n",
        "    best_float_model = tf.keras.models.load_model(MODEL_SAVE_PATH)\n",
        "    \n",
        "    # Bọc mô hình với QAT (Chỉ bọc các layer an toàn, bỏ qua TFOpLambda gây lỗi)\n",
        "    def apply_quantization_to_layer(layer):\n",
        "        if type(layer).__name__ in ['TFOpLambda', 'SlicingOpLambda'] or 'tf.__operators__' in layer.name:\n",
        "            return layer\n",
        "        if isinstance(layer, tf.keras.layers.Rescaling):\n",
        "            return layer.__class__.from_config(layer.get_config())\n",
        "        try:\n",
        "            return tfmot.quantization.keras.quantize_annotate_layer(layer)\n",
        "        except Exception:\n",
        "            return layer\n",
        "\n",
        "    annotated_model = tf.keras.models.clone_model(\n",
        "        best_float_model,\n",
        "        clone_function=apply_quantization_to_layer\n",
        "    )\n",
        "    q_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model)\n",
        "    \n",
        "    q_aware_model.compile(\n",
        "        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),\n",
        "        loss=tf.keras.losses.SparseCategoricalCrossentropy(),\n",
        "        metrics=['accuracy']\n",
        "    )\n",
        "    \n",
        "    callbacks_qat = [\n",
        "        tf.keras.callbacks.ModelCheckpoint(filepath=QAT_MODEL_SAVE_PATH, save_best_only=True, monitor='val_accuracy'),\n",
        "        tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)\n",
        "    ]\n",
        "    \n",
        "    q_aware_model.fit(train_ds, validation_data=val_ds, epochs=QAT_EPOCHS, callbacks=callbacks_qat)\n",
        "    \n",
        "    print(\"\\n--- Đánh giá mô hình QAT trên Test Set ---\")\n",
        "    test_ds = create_dataset_from_paths(X_test, y_test, is_training=False)\n",
        "    test_loss, test_acc = q_aware_model.evaluate(test_ds)\n",
        "    print(f\"-> Độ chính xác trên Test Set (Của bản QAT): {test_acc*100:.2f}%\\n\")\n",
        "    \n",
        "    from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay\n",
        "    y_pred_probs = q_aware_model.predict(test_ds)\n",
        "    y_pred = np.argmax(y_pred_probs, axis=1)\n",
        "    \n",
        "    print(\"\\nBáo cáo phân loại (Classification Report):\")\n",
        "    print(classification_report(y_test, y_pred, target_names=CLASS_NAMES))\n",
        "    \n",
        "    cm = confusion_matrix(y_test, y_pred)\n",
        "    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=CLASS_NAMES)\n",
        "    fig, ax = plt.subplots(figsize=(8, 8))\n",
        "    disp.plot(cmap=plt.cm.Blues, ax=ax, xticks_rotation=45)\n",
        "    plt.title('Confusion Matrix (QAT Model)')\n",
        "    \n",
        "    image_dir = os.path.join(OUTPUT_DIR, 'image')\n",
        "    os.makedirs(image_dir, exist_ok=True)\n",
        "    plt.savefig(os.path.join(image_dir, 'confusion_matrix_qat.png'))\n",
        "    plt.show()\n",
        "else:\n",
        "    print(\"Hủy quá trình train do không tìm thấy dữ liệu.\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# --- 5. EXPORT TFLITE (FLOAT16 & INT8) ---\n",
        "if len(filepaths) > 0:\n",
        "    print(\"5.1 Xuất mô hình gốc sang TFLite Float16...\")\n",
        "    best_float_model = tf.keras.models.load_model(MODEL_SAVE_PATH)\n",
        "    converter_fp16 = tf.lite.TFLiteConverter.from_keras_model(best_float_model)\n",
        "    converter_fp16.optimizations = [tf.lite.Optimize.DEFAULT]\n",
        "    converter_fp16.target_spec.supported_types = [tf.float16]\n",
        "    tflite_fp16_model = converter_fp16.convert()\n",
        "    fp16_save_path = TFLITE_SAVE_PATH.replace('.tflite', '_FP16.tflite')\n",
        "    with open(fp16_save_path, 'wb') as f:\n",
        "        f.write(tflite_fp16_model)\n",
        "        \n",
        "    print(\"5.2 Xuất mô hình QAT sang TFLite INT8...\")\n",
        "    # Load lại QAT model (phải dùng quantize_scope để đọc được)\n",
        "    with tfmot.quantization.keras.quantize_scope():\n",
        "        best_qat = tf.keras.models.load_model(QAT_MODEL_SAVE_PATH)\n",
        "        \n",
        "    converter_int8 = tf.lite.TFLiteConverter.from_keras_model(best_qat)\n",
        "    converter_int8.optimizations = [tf.lite.Optimize.DEFAULT]\n",
        "    \n",
        "    def representative_dataset():\n",
        "        # Dùng toàn bộ ảnh Validation để lấy mẫu hoàn hảo nhất\n",
        "        for images, _ in val_ds:\n",
        "            yield [images]\n",
        "            \n",
        "    converter_int8.representative_dataset = representative_dataset\n",
        "    converter_int8.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]\n",
        "    converter_int8.inference_input_type = tf.uint8\n",
        "    converter_int8.inference_output_type = tf.uint8\n",
        "\n",
        "    tflite_quant_model = converter_int8.convert()\n",
        "    int8_save_path = TFLITE_SAVE_PATH.replace('.tflite', '_INT8.tflite')\n",
        "    with open(int8_save_path, 'wb') as f:\n",
        "        f.write(tflite_quant_model)\n",
        "            \n",
        "    print(\"\\n=== HOÀN THÀNH TẤT CẢ ===\")\n",
        "    print(f\"Các file đã được lưu tại thư mục: {OUTPUT_DIR}\")\n",
        "    print(f\"1. Mô hình Float32 gốc: {MODEL_SAVE_PATH}\")\n",
        "    print(f\"2. TFLite Float16 (An toàn, siêu nhanh trên GPU): {fp16_save_path}\")\n",
        "    print(f\"3. Mô hình QAT Keras: {QAT_MODEL_SAVE_PATH}\")\n",
        "    print(f\"4. TFLite INT8 (Nhẹ nhất, tối ưu CPU): {int8_save_path}\")\n",
        "    print(\"Bạn có thể tải các file TFLite về để chạy thử!\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# --- 6. CHẤM ĐIỂM TFLITE TRÊN TẬP TEST ---\n",
        "import time\n",
        "\n",
        "def evaluate_tflite(tflite_path):\n",
        "    if not os.path.exists(tflite_path): \n",
        "        print(f\"Không tìm thấy {tflite_path}\")\n",
        "        return\n",
        "        \n",
        "    print(f\"\\n--- Đang đánh giá: {os.path.basename(tflite_path)} ---\")\n",
        "    interpreter = tf.lite.Interpreter(model_path=tflite_path)\n",
        "    interpreter.allocate_tensors()\n",
        "    \n",
        "    input_details = interpreter.get_input_details()[0]\n",
        "    output_details = interpreter.get_output_details()[0]\n",
        "    \n",
        "    test_filepaths = np.load(os.path.join(OUTPUT_DIR, 'test_filepaths.npy'))\n",
        "    test_labels = np.load(os.path.join(OUTPUT_DIR, 'test_labels.npy'))\n",
        "    \n",
        "    correct = 0\n",
        "    total = len(test_filepaths)\n",
        "    \n",
        "    start_time = time.time()\n",
        "    for i in range(total):\n",
        "        img_string = tf.io.read_file(test_filepaths[i])\n",
        "        img = tf.image.decode_jpeg(img_string, channels=3)\n",
        "        img = tf.image.resize(img, IMG_SIZE)\n",
        "        \n",
        "        if input_details['dtype'] == np.float32:\n",
        "            input_data = np.expand_dims(img, axis=0).astype(np.float32)\n",
        "        elif input_details['dtype'] == np.uint8:\n",
        "            input_data = np.expand_dims(img, axis=0).astype(np.uint8)\n",
        "            \n",
        "        interpreter.set_tensor(input_details['index'], input_data)\n",
        "        interpreter.invoke()\n",
        "        output_data = interpreter.get_tensor(output_details['index'])\n",
        "        \n",
        "        pred = np.argmax(output_data[0])\n",
        "        if pred == test_labels[i]:\n",
        "            correct += 1\n",
        "            \n",
        "        if (i+1) % 50 == 0:\n",
        "            print(f\"  ... Đã chấm {i+1}/{total} ảnh\")\n",
        "            \n",
        "    end_time = time.time()\n",
        "    acc = correct / total\n",
        "    print(f\"=> HOÀN THÀNH! Độ chính xác: {acc*100:.2f}%\")\n",
        "    print(f\"=> Tốc độ CPU: {(end_time - start_time) / total * 1000:.1f} ms/ảnh\")\n",
        "\n",
        "    print(\"\\n--- Trực quan hóa 6 ảnh ngẫu nhiên ---\")\n",
        "    indices = np.random.choice(total, 6, replace=False)\n",
        "    plt.figure(figsize=(10, 6))\n",
        "    for idx, i in enumerate(indices):\n",
        "        img_string = tf.io.read_file(test_filepaths[i])\n",
        "        img = tf.image.decode_jpeg(img_string, channels=3)\n",
        "        img_resized = tf.image.resize(img, IMG_SIZE)\n",
        "        \n",
        "        if input_details['dtype'] == np.float32:\n",
        "            input_data = np.expand_dims(img_resized, axis=0).astype(np.float32)\n",
        "        else:\n",
        "            input_data = np.expand_dims(img_resized, axis=0).astype(np.uint8)\n",
        "            \n",
        "        interpreter.set_tensor(input_details['index'], input_data)\n",
        "        interpreter.invoke()\n",
        "        output_data = interpreter.get_tensor(output_details['index'])\n",
        "        pred_class = np.argmax(output_data[0])\n",
        "        true_class = test_labels[i]\n",
        "        \n",
        "        plt.subplot(2, 3, idx + 1)\n",
        "        plt.imshow(img.numpy().astype('uint8'))\n",
        "        color = 'green' if pred_class == true_class else 'red'\n",
        "        plt.title(f\"True: {CLASS_NAMES[true_class]}\\nPred: {CLASS_NAMES[pred_class]}\", color=color)\n",
        "        plt.axis('off')\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "try:\n",
        "    evaluate_tflite(fp16_save_path)\n",
        "    evaluate_tflite(int8_save_path)\n",
        "except Exception as e:\n",
        "    pass"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}

with open(os.path.join(os.path.dirname(__file__), 'kaggle_train_mobilenetv3_QAT.ipynb'), 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)
print('Successfully generated kaggle_train_mobilenetv3_QAT.ipynb')
